# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bXYeWutvT59gub7rGF5mChQxO-UDScaL
"""

import pandas as pd

# DataFrame yaratamiz
data = {
    'Ism': ['Ali', 'Vali', 'Sardor', 'Diyor', 'Nodir'],
    'Yoshi': [25, 30, 22, 27, 24],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro', 'Toshkent', 'Samarqand']
}

df = pd.DataFrame(data)

# Yuqoridagi DataFrame'ni ko'rish
print("Asl DataFrame:")
print(df)

# Yoshi 25 dan katta bo'lganlarni filtrlaymiz
filtered_df = df[df['Yoshi'] > 25]

# Filtrlangan DataFrame'ni ko'rsatamiz
print("\nYoshi 25 dan katta bo'lganlar:")
print(filtered_df)